spring:
  server:
    use-forward-headers: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://loveplace-database.c5m9nthmvewx.ap-northeast-2.rds.amazonaws.com:3306/sol?useSSL=false
    username: admin
    password: wjdthf1212
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always # 서버 시작시 항상 classpath의 sql문을 실행하도록 설정
      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      data-locations: classpath:init.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정
      schema-locations: classpath:init.sql # 서버 시작시 ddl sql문을 실행할 위치 및 파일 지정

  messages:
    basename: errors
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"

cloud:
  aws:
    credentials:
      accessKey: AKIASU6RXFFGFDWEAXVD
      secretKey: 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
    s3:
      bucket: loveplace-deploy
    region:
      static: ap-northeast-2
    stack:
      auto: false