spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/love
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  profiles:
    include: oauth
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"